sonata_admin:
    title: 'Administration'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            users:
                label: ~
                label_catalogue: ~
                items:
                    - route: user_admin_people
                      label: People.

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
