sonata_admin:
    title: 'Administration'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
        groups:
            administration:
                label: messages.admin.label
                label_catalogue: messages
                icon:            '<i class="fa fa-cogs"></i>'
                items:
#                    - route: user_admin_people
#                      label: People (Drupal)
#                      admin: app.sonata.admin.user
#                      roles:
#                         -
                    - app.sonata.admin.user

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
